version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install flake8
          command: pip install flake8
      - run:
          name: Lint with flake8
          command: flake8 .

workflows:
  lint-workflow:
    jobs:
      - lint