version: 2.1

orbs:
  github-super-linter: circleci/github-super-linter@1.0

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10
    working_directory: ~/project

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
  lint:
    executor: python-executor
    steps:
      - checkout
      - github-super-linter/lint:
          scan-dir: .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build